### ISSUE TITLE
How to use withUIWebView?

### ISSUE THREAD

**Issue by zhouzizi** [dpogue/cordova-plugin-webp#3]
Have any demo?

**Comment by dpogue** [comment]
It should be as easy as running `cordova plugin add cordova-plugin-webp` and then referencing a WebP image in your HTML.

For testing, I usually run `cordova create <projectname>` to generate the default "Hello World" app, and then change the cordova logo from a PNG to a WebP image. If the plugin is not installed, you'll get a blank image because it will fail to load. If the plugin is working, the WebP will render correctly.
