### ISSUE TITLE
Ionic use

### ISSUE THREAD

**Issue by jeybs** [dpogue/cordova-plugin-webp#9]
Hi, can you provide sample on how to use this for ionic framework? am i just install it? no other config or import needed?

**Comment by dpogue** [comment]
Hi @jeybs
With the current version of Ionic using the default iOS webview (UIWebView), you should be able to just install it and it will work automatically.

It will not work with the WKWebView plugin, which might become the default webview in a future version of Ionic (so that's something to be aware of).
